### ISSUE TITLE
vip antiban imminity

### ISSUE THREAD

**Issue by panikajo** [J-Tanzanite/Little-Anti-Cheat#1]
dude if I use a vip plugin that provides my VIP players to their bunnyhop their ban can you add immunity to this?

**Comment by J-Tanzanite** [comment]
Hmm, yeah that seems like something I should look into adding.
What Bhop plugin do you use?

**Comment by panikajo** [comment]
> What Bhop plugin do you use?

This https://hlmod.ru/resources/vip-bhop.1206/
source https://paste.kruzya.me/anovolopar.cpp
 and vip core systems..

github link https://github.com/R1KO/VIP-Core

all VIP privileges work through groups

**Comment by J-Tanzanite** [comment]
Alright, I've added a new forward that can be used for blocking cheat detections for specific players.

I decided to do it this way because there are many plugins out there, and adding a special case for all of them would be tedious and a hassle for everyone.
Adding a simple forward that any plugin can block is the easiest and most efficient way, afaik.

This does mean that you have to either add the forward to the VIP Core plugin itself, or compile a new plugin that checks if a player is in the VIP group, and if so, return Plugin_Stop if cheat is 4.
This is the forward btw:
`public Action lilac_allow_cheat_detection(int client, int cheat)`

I did try to read the code, but unfortunately, I found it somewhat confusing...
So you should contact the author of the bhop plugin, or someone who can read the code T~T

It **MIGHT** work if you add this at the end of _anovolopar.cpp_ (Shouldn't it be .sp?)
```
#define LILAC_BHOP 4

public Action lilac_allow_cheat_detection(int client, int cheat)
{
	if (cheat == LILAC_BHOP && VIP_IsClientFeatureUse(client, g_sFeature))
		return Plugin_Stop;

	return Plugin_Continue;
}
```

**Comment by J-Tanzanite** [comment]
I'm going to assume this issue has been solved, considering you gave me a thumbs up and haven't said anything further.

Going to leave this issue open for a few more days in case there is anything you want to add or say. :)
