### ISSUE TITLE
Undetected aimbot for three maps

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#107]
I join you the demo just look "The baran" player as Nick (L4D2), I think the shaking of his aim just block the detection maybe. I had a little older version  but it does not seem to have received any major update anyway.

https://drive.google.com/file/d/1yWMFNvjL80I1u-nd0870zPeIRJMoUTUj/view?usp=sharing

**Comment by J-Tanzanite** [comment]
The small shaking we see does seem to be nospread. However, nospread "shaking" is not large enough to trigger the total-delta aimbot check, which is not surprising.

As for his larger snaps, might be some smoothing going on (hard to tell because STV/Spectating has limitations), or it may be something else, hard to tell.

With that said, support for L4D1&2 has always been somewhat questionable...
I haven't done a lot of testing with it (if any at all), people have just told me Lilac works in L4D 1&2...
Which is weird because when I tested it, L4D2 didn't fire kill events (required for aimbot detection) upon a kill on bots... Sooo... I always found that weird.

I have to say, having two issues open for the same thing is... Useless and causes a mess with me replying... I think I may close the other issue and mark it as a duplicate, just to keep things organized and easier to follow. :/
