### ISSUE TITLE
L4D2 Undetected aimbot on player

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#108]
There is obviously a bypass that has been found somehow (a simple search and you will see), nothing surprising as it is open source. His friend with chinese nickname got logged tho so maybe they did not have the same cheat, the funny thing is that it was almost impossible to see that the chinese player was cheating but the more obvious one is not detected ?
Not related but you can even see him use a teleport hack above the second fire for not taking damage.

https://streamable.com/28fpgb

**Comment by J-Tanzanite** [comment]
I realize now that in my last reply, I came off wrong...

I came off as peeved, which I'm not.
I just simply at the moment, don't have a lot of time (You're kinda lucky rn, as right NOW I have some time, lol)...
So I have to write in a hurry and then get back to stuff going on in my life. Nothing serious or bad going on in my life (quite the contrary), I'm just really busy.
That kinda just leaves me to be more... Abrupt and less clear about how things are.

---

With that out of the way, at the time SMAC were made, I wasn't around in the anti-cheat scene, nor in the cheating scene... But if you look at the history of SMAC, and their actual code, it's clear they didn't think some stuff through (Or at least, they left some... questionable design decisions).

Their aimbot detection code is a great example of this, because they do this check: https://github.com/Silenci0/SMAC/blob/master/addons/sourcemod/scripting/smac_aimbot.sp#L348
...
This is just a bad idea... And leads to an extremely simple bypass... This has been known for a LOOONG time now, and I'm not exactly revealing "new" or hidden information here.

But even if we fixed that, and made it not exploitable...
Their method for detecting aimbots were just bad in the first place... Detecting snaps via detecting an angle delta larger than 45 degrees is... Not great.
Packetloss (or just lag) can cause false positives, especially for players with a higher sensitivity (which is why the value is so high in the first place, and it's still fairly low)...
Heck, some players don't even need bad internet to cause false positives, as this method of detecting "snaps" can falsely trigger on high sensitivity players.
And cheats can bypass this by just restricting their aimbot to be less than 45 degrees... Or do BARELY any smoothing at all...

I think I understand why they did it this way, as a lot of aimbots at the time were less sophisticated than they are now, but this method of detecting aimbots is outdated, and has issues. It's not useless per say, but it's not great.
So `but i don't think that they were inefficient too when they coded that, the proof if we believe in the website i shared.` - I have to disagree with.

---

>so LAC does not detect whatever is "psilent"?

No, Lilac does, but it's not called "psilent" in Lilac, it's referred to as "Angle-Repeat" due to how Psilent tends to work and the history behind it.
However, it's in the name how you would bypass it (not hard). As I mentioned in the other issue you raised, I'm considering tweaking some of the values Lilac uses to be less cautious, so it would detect more easily. But we'll see. I would have to wait anyway, because I'd rather update Lilac's methods after a lot of cheats have finally gotten a proper bypass, before adding or fixing Lilac to be good again... This is just so Lilac remains useful for the most amount of time for most community servers.

---

At the end of the day tho, it's your server, and if you'd rather use SMAC - you do that.
