### ISSUE TITLE
[Request] Logging to a database

### ISSUE THREAD

**Issue by JokeySPCT** [J-Tanzanite/Little-Anti-Cheat#12]
Is it possible we can get logging to a database as a secondary option to a text file? Infact, if I fork and add it and make a merge request is there a possibility of it being accepted?

**Comment by J-Tanzanite** [comment]
I wasn't even aware that logging to a database was a thing, but it sounds like something a lot of people might find useful.

Sure, I wouldn't mind adding it, only problem being I don't know how to do that, and I assume it requires some SQL (Something I'm unfamiliar with).
As for forking and merging, that would be great! As I have no way to test for such a thing, it would be nice if you could to that.
And yeah, I would merge and credit you for the functionality :)

There may be one problem tho, I plan on finishing version 1.5.0 in my development branch, it's long overdue and I wanna get it out without adding something that might break it for server owners.
Just to have finished the version for once and cleaned up my mess (explained here: https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/6#issuecomment-624717728 && https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/development/README.md)

So I would merge your functionality in version 1.6.0.

**Comment by m4rkey** [comment]
Great, I can fork it and get started on database logging, as a separate option.

**Comment by m4rkey** [comment]
After looking at some of your stuff, would simple logging suffice? As such, the server owner can decide whether or not they want database logging with a CVAR if they do instead of writing the log to a text file, it would push the whole log to a database with timestamps?

**Comment by J-Tanzanite** [comment]
Having a ConVar to enable or disable logging to a database would be necessary, as some admins may not need it. And some may decide to use both logging to a file and logging to a database.

One thing I am thinking about is how Lilac currently handles formatting of logs.
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/lilac.sp#L1533

Currently Lilac checks if it should format a line to a log if `icvar[CVAR_LOG]` is 1
I think the most efficient and cleanest way of adding DB logging is to change every instance of:
```
if (icvar[CVAR_LOG]) {
```
with:
```
if (icvar[CVAR_LOG] || icvar[CVAR_LOG_DB]) {
```

All instances where a line is to be logged to a file, is done through this function: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/lilac.sp#L1803
Meaning you could easily change the function from this:
```
void lilac_log(bool cleanup)
{
	/* Log to file code */
}
```
With:
```
void lilac_log(bool cleanup)
{
	if (icvar[CVAR_LOG]) {
		/* Log to file code */
	}

	if (icvar[CVAR_LOG_DB]) {
		/* Log to DB */
	}
}
```

This should be the easiest and cleanest way of implementing logging to a database.
However, does include the date to get logged as well. I've never used database logging, so I don't know if that's a problem. I suspect that it's not and that this method should be good enough.

**Comment by m4rkey** [comment]
Hi! Thanks. I have almost completed basic functionality for this. However, a few problems have raised. Since we use CVARS, and I have defaulted logging database to 0 by default, Even if its in the config it wont be loaded, since the CVAR is changed after OnPluginStart is called.

We can fix this, by moving lilac_log_first_time_setup() and ensuring this runs only once inside OnConfigsExecuted() which is called when all configs etc have been loaded.

Are you fine with this?

**Comment by J-Tanzanite** [comment]
Sorry for my late reply, but I'm not sure what you mean here

**Comment by m4rkey** [comment]
I have already completed a basic version of this on my fork, that better explains what I was doing.

**Comment by J-Tanzanite** [comment]
Ahh, you uploaded the code.
I see what you mean now, and yeah, moving lilac_log_first_time_setup() is perfectly fine :)

However, I looked at your code and I noticed a few things which would cause issues under the current implementation, mainly this function: 
``` c
void lilac_log(bool cleanup)
```

Will also log this: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/lilac.sp#L1835
to the SQL server... Which I didn't think about.
... Big brain moment from me.
I think sending that to the SQL server is overkill.

In addition to this, I am not a fan of this:
``` c
if (icvar[CVAR_LOG_EXTRA] == 2 && !icvar[CVAR_DBLOG])
```
As this would cause extra logging (to file) to fail if database logging is also enabled.

I think a better way of going about this is to change the logging function to accommodate this instead:
``` c
void lilac_log(bool cleanup, bool relay)
{
	if (icvar[CVAR_DBLOG] && relay) {
		/* Log to SQL */
	}

	if (icvar[CVAR_LOG]) {
		/* Log to file */
	}
}
```
And doing this instead:
``` c
	if (icvar[CVAR_LOG_EXTRA] == 2)
		lilac_log_extra(client, false, false);
```
And lastly, because we need to carry over that information:
``` c
void lilac_log_extra(int client, bool cleanup, bool relay)
{
	/* Formatting extra information. */

	lilac_log(cleanup, relay);
}
```

I think this would solve both problems fairly easily, while keeping the door open for future additions, like Discord logging, IRC etc.

I can't believe I didn't think about this harder before, as this has caused more trouble than it should have, sorry about that.

---

There are some small details which I also don't like, like this:
``` c
Database playerinfo_database = null;
bool playerinfo_databaseConnected = false;
```

These are not *"playerinfo"*, and shouldn't be named as such, should probably go under *"misc"*.
Oh and capitalization *"databaseConnected"* makes me sad. :c 

---

There is one extra problem, which has to be discussed, I completely understand if **THIS** isn't something you wanna deal with.
https://github.com/m4rkey/Little-Anti-Cheat/commit/8ba1e1c917769b74ad53d91d14e42be29505f66c
What happened to the spacing?

I'm sadly one of those who try to have consistent spacing and syntax rules (tho I am not perfect).
I'm assuming your IDE did this, as I can't imagine you changing everything manually.

I think the easiest way of fixing this would be for me to manually add your changes (and not the spacing) and give you credit. That way, you don't have to fix the space issues.
Tho, that might create problems when it comes to github and crediting? (Contributions)

I'm not super familiar with Github, so I might be wrong there, and there might be a simpler solution.

**Comment by m4rkey** [comment]
SPEdit isnt my favorite editor, but it just automatically fixed all the spacing so it wouldnt throw compile editors, I see the feedback now though and will get to work.

**Comment by m4rkey** [comment]
I am going to re-fork the repo and start over, and write it in a better way so we dont have issues.

**Comment by J-Tanzanite** [comment]
Sure, btw, I think we need to coordinate better.
I'm currently sitting on version 1.6.0-Dev 1, for my developmental branch.

It would be easiest of we both agree on which version to work on together, so that merging your changes won't be needlessly difficult.

I noticed you haven't forked yet, but I'm assuming you have a local version with your changes.
If you haven't gotten around to it yet (No worries btw), then maybe I should update my developmental branch with 1.6.0-Dev 1, and then you fork from that and add database logging.

If however, you are already working on 1.5.1 with the database logging, then I will wait for your merge request. :)

I'll wait a few days for an answer, if you don't say anything, then I'm going to assume you've been busy with life (Again, no worries) and haven't forked/began working on it yet, and I will update the developmental branch with version 1.6.0-Dev 1

**Comment by BrutalCSEjziponken** [comment]
I like the idea of MYSQL logging. I would use it. :)

**Comment by J-Tanzanite** [comment]
It's been 3 weeks since your last reply.
I'm going to assume you've gotten busy or have abandoned the idea.
Either way, thank you for trying and for being a fam :)

I'm going to close this issue, if you wish to return to this, just reopen the issue.
