### ISSUE TITLE
Problems mysql

### ISSUE THREAD

**Issue by Truyn** [J-Tanzanite/Little-Anti-Cheat#122]
Text is crooked
![image](https://user-images.githubusercontent.com/53527324/174300008-cbda6ddb-75fc-4091-b239-d2289adf1d78.png)

**Comment by azalty** [comment]
There seems to be a problem indeed.

Are you using a distant mysql database? It is possible that you didn't set the charset to UTF-8.

**Comment by Truyn** [comment]
the default is utf8 with other analogues I have no problems

so the problem is definitely not mysql settings

**Comment by azalty** [comment]
Here is the part responsible for the handling of names https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/development/scripting/lilac/lilac_database.sp#L110-L119

I don't see any problem in the code

> the default is utf8 with other analogues I have no problems

In older version of mysql, the default charset was `latin1` instead of `utf8mb4` ([5.7](https://dev.mysql.com/doc/refman/5.7/en/charset.html) - [8.0](https://dev.mysql.com/doc/refman/8.0/en/charset.html))

Not sure what 'analogue' means, sorry, I have very minimal knowledge in SQL, and I was the one who added database support to LilAC.

From the code side, everything seems correct. Not sure what the problem is.

**Comment by J-Tanzanite** [comment]
I've seen this pattern of `Ð¿°¡Ñ` character spam in many different situations for years now, and it's an encoding issue, not a Lilac issue. Specifically, when you see these letters being spammed, it's typically due to Cyrillic letters (ex Russian) encoded in UTF-8 being misread as Latin-1.

If you look at this player's name history on steam, he was at one point named "Zxc Стёпа" (This is correctly encoded in UTF-8). But your DB server gets those bytes, and assumes it's Latin-1, which means it discards some bytes (as they are not visible in Latin-1) and produces the mess: `Zxc Ð¡ÑÑÐ¿Ð°`

So it's a DB server config issue.

**Comment by Truyn** [comment]
Unfortunately, I'm from Russia, and I absolutely disagree with you about the database configuration.

![image](https://user-images.githubusercontent.com/53527324/174410994-2943c5bd-02be-4f2c-aed0-c86eb1f5750b.png)

I use a lot of db plugins and the problem is only with yours at the moment.
It is logical to assume that if the configuration was not correct, then the problem would be with all plugins, including sourcebans and so on.

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/174411123-1190544d-9104-4c4b-9311-50d8e484dd42.png)

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/174411209-137cd013-f7da-40af-af91-f4cb7c7d5365.png)
For the shavit timer example, as we can see, everything works correctly as in other cases.

**Comment by azalty** [comment]
what's the charset for shavit timer?

**Comment by Truyn** [comment]
> I think SourceMod handles sql requests itself, so maybe you have an old SM version that runs an old version of MySQL? Not sure how it works.

 SourceMod Version: 1.10.0.6540

**Comment by Truyn** [comment]
> what's the charset for shavit timer?

![image](https://user-images.githubusercontent.com/53527324/174411337-3b3579c7-4896-4bfe-bc9c-26c7b23c991f.png)

**Comment by azalty** [comment]
Thanks for sharing all these infos. I'll take a look at how shavit-timer handles name storing.

**Comment by azalty** [comment]
What source game are you running?

**Comment by Truyn** [comment]
csgo

**Comment by azalty** [comment]
shavit/bhoptimer doesn't seem to use really different things

https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-core.sp#L2673-L2679
They use this function for getting names: https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/include/shavit/core.inc#L478-L519 - but I guess the problem would only be at the last character? So that seems weird.

I can confirm there is an issue with your database.

Notepad++, writing `ДрАгОвИч` with `UTF-8`:
![image](https://user-images.githubusercontent.com/36737524/174411876-106901a5-bfc7-4045-b676-62d93a276bb6.png)
Notepad++, changing encoding to `ANSI`:
![image](https://user-images.githubusercontent.com/36737524/174411916-01f3b2f7-b308-42e8-9df9-55f854ab7a06.png)

This matches the username in the database. There's definitely a problem somewhere, and it doesn't seem to come from LilAC as it is a classical method that is used. I've personally never encountered problems with it, and I've used it everywhere.

**Comment by Truyn** [comment]
well, let the problem remain

I don't know what to answer :D

**Comment by Truyn** [comment]
I have 10+ mysql plugins.............................

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/174412473-0a54a9db-9d12-4640-bda0-bd8830d906cc.png)
![image](https://user-images.githubusercontent.com/53527324/174412488-05e833e5-e16b-4453-8156-a63aab4bdbfc.png)
![image](https://user-images.githubusercontent.com/53527324/174412494-09b2cc69-043f-4715-acb1-b0f1646aaf8b.png)
![image](https://user-images.githubusercontent.com/53527324/174412526-32bb0848-151c-4a58-92af-acace6abe525.png)
![image](https://user-images.githubusercontent.com/53527324/174412543-781a06d2-f4d4-4c90-8a0e-f02dbb039c34.png)

**Comment by Truyn** [comment]
I'm not a programmer, but I don't even see in the source code where you set the encoding, although I see it in the shavit sources

**Comment by azalty** [comment]
I don't know what to answer too, I don't see any bug in my code, I don't see anything that could cause that.

Someone help pls.

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/174412769-a0b5e847-ceeb-4169-a0e8-5b3aeeabc4ff.png)

**Comment by azalty** [comment]
> I'm not a programmer, but I don't even see in the source code where you set the encoding, although I see it in the shavit sources

That is because we don't set it. I don't know a thing about that, but I expect you to set it.

> ![image](https://user-images.githubusercontent.com/53527324/174412769-a0b5e847-ceeb-4169-a0e8-5b3aeeabc4ff.png)

Didn't even know this was a thing lol, never had to use it. I'll set the charset to "utf8mb4".
From what I read, this is still a DB issue though. The connections to your database default to latin1, and they should default to utf8mb4

Btw I think "utf8mb4_general_ci" is a collation rule, not a charset. "utf8mb4" is a charset.

**Comment by Truyn** [comment]
Ok, thx

**Comment by Truyn** [comment]
![Screenshot_2022-06-18-04-18-57-06_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174417011-cc5cb8e2-2104-4bee-a1b3-ea5243a06213.jpg)
![Screenshot_2022-06-18-04-20-30-86_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174417014-8b6deef6-b2bd-4071-ad8d-b643a9305b35.jpg)
![Screenshot_2022-06-18-04-18-32-77_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174417015-79434a4a-aa75-4825-8b8c-87bafe78e390.jpg)

**Comment by Truyn** [comment]
> > I'm not a programmer, but I don't even see in the source code where you set the encoding, although I see it in the shavit sources
> 
> That is because we don't set it. I don't know a thing about that, but I expect you to set it.
> 
> > ![image](https://user-images.githubusercontent.com/53527324/174412769-a0b5e847-ceeb-4169-a0e8-5b3aeeabc4ff.png)
> 
> Didn't even know this was a thing lol, never had to use it. I'll set the charset to "utf8mb4". From what I read, this is still a DB issue though. The connections to your database default to latin1, and they should default to utf8mb4
> 
> Btw I think "utf8mb4_general_ci" is a collation rule, not a charset. "utf8mb4" is a charset.

![Uploading Screenshot_2022-06-18-04-20-30-86_3d419158bad5872c40592a6c9956e692.jpg…]()

**Comment by Truyn** [comment]
![Screenshot_2022-06-18-04-18-32-77_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174418062-56cb2eef-c872-410e-89cf-35081221d2dc.jpg)

**Comment by Truyn** [comment]
No latin1, i check cfg
![Screenshot_2022-06-18-04-20-30-86_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174418074-648f3d17-e539-47c3-aaab-8527c188dacf.jpg)
![Screenshot_2022-06-18-04-18-57-06_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174418075-96480589-9435-4c3d-8793-4ca0d5dcd678.jpg)
![Screenshot_2022-06-18-04-18-32-77_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/53527324/174418076-389171bb-8043-4e10-9a60-d0d3d2e10129.jpg)

**Comment by azalty** [comment]
Yea that's weird, it should work
