### ISSUE TITLE
[Question] Anti-Aim

### ISSUE THREAD

**Issue by JokeySPCT** [J-Tanzanite/Little-Anti-Cheat#13]
Does this cheat support detecting Anti-Aims? I tested it earlier with a variety of cheats and it didn't seem to be the case, if not is this a planned feature at a later date?

**Comment by J-Tanzanite** [comment]
Lilac detects simple Angle Exploits, like Pitch AA and Roll exploits, but it doesn't check for Yaw Anti-Aim.

I'm assuming you tested this in CS:GO.
CS:GO Handles anti-aims very differently from that of other source games, Pitch AA isn't common, and mostly don't go outside of the normal player range, which is what Lilac checks for.

There used to be Yaw Anti-Aim detection in Lilac in the past (Private version), but the Yaw AA was removed, since it was only compatible with source games that weren't CS:GO.

I do plan on adding back Yaw Anti-Aim detection, and making it compatible with CS:GO, but I'm not sure when I'll do it.
