### ISSUE TITLE
Add option to exclude scroll from macro detection

### ISSUE THREAD

**Issue by Sicquze-samurai** [J-Tanzanite/Little-Anti-Cheat#133]
The fact is that if you use macro detection, then when you jump on the wheel, the anti-cheat wants to kick you for it.
I changed the value to 0 because I didn't want players to kick for it, but I wouldn't want to deprive the server of additional protection from bunnyhop.

**Comment by J-Tanzanite** [comment]
Players using jump macros will get kicked because `lilac_macro_method` is set to 0, which kicks, the only other method is 1, which bans (temporarily).

The offending player using the macro/scroll will get a warning, as `lilac_macro_warning` defaults to 1, which warns the player to stop before they get kicked. You can change it to 2 to warn admins or 3 to warn everyone on the server.

I'm assuming you'd like other `lilac_macro_method` options, like blocking jumping for a while or penalizing the player in some other way, rather than kicking?

**Comment by Sicquze-samurai** [comment]
I just don't consider scrolling to be macros, because the game itself allows you to use the mouse wheel.

**Comment by J-Tanzanite** [comment]
There may be a way to do exclude scroll binds, but I'm not entirely sure about it, would have to do some tests.
Sadly, I am a little busy atm with some IRL stuff, but I'll look into it.

**Comment by J-Tanzanite** [comment]
One issue with adding this as an option is that it would in some cases, cause actual scripts and macros to bypass detection.

While there is a difference between scroll and macros, allowing one but not the other seems like a rather strange request...
They both do the same thing, spam an input (even if the efficiency and game intention isn't the same).
If someone gets kicked for macro, they can just join back later and use scroll, why exactly would you not want Macros, but be fine with scroll?

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies, feel free to reopen this issue if you have a response to my questions above.
For now, I don't see a good reason for this request.
