### ISSUE TITLE
Update aimbot detection please

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#135]
It is bypassed 100% i say it since months, and when you catch one cheater this is just luck because of another module that has nothing to do with it or because of human work by watching demos.

https://streamable.com/92jt92

Ignored by lilac:
https://streamable.com/7q1rqr
https://streamable.com/wuwjc5 (january 2022)
https://streamable.com/28fpgb (october 2021)

**Comment by J-Tanzanite** [comment]
Yeah Lilac has been out there for a few years now; so cheats have begun to catch up.
Currently, I am a little busy with some IRL stuff, but yes, I'll add this to my todo list for when I get some time. :)

I would have worked more on Lilac had I actually been payed for these things lol, I won't prioritize free work over payed work, friends and family; it's just how life is.

That said, L4D(1&2) support has always been a little iffy, due to how L4D works.
The good news is that I know of some things I could do, but again, it will be a while until that gets done.

I will close this issue, as this is more fitting to have on the discussion page than here, and the spam over this is getting a little annoying. Also, continuously showing video clips of this doesn't aid development, as aim detection is a lot more complicated than you think, and videos don't give much to work with.
I don't know when I'll return to working on this, as things are a little hectic rn, but it is coming.
