### ISSUE TITLE
[Request] Add command block feature

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#139]
These ones are totally skipped by AddCommandListener, pretty sure some are used to cheat or lag the server.

drawcross
drawline
dump_entity_sizes
dumpentityfactories
dumpgamestringtable
editdemo
endround
groundlist
listmodels
mem_dump
report_entities
report_touchlinks
respawn_entities
snd_restart
soundlist
sv_soundscape_printdebuginfo

**Comment by J-Tanzanite** [comment]
Where did you get this list from?
Because some of these commands can't lag the server, and I speculate some of these would be blocked by the server by default?

`snd_restart` just restarts sounds in your game, which is common in games like TF2, where audio sometimes gets broken and loops uncontrollably.

Where you getting this from?
