### ISSUE TITLE
Questions regarding Macro detection.

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#143]
Can there be false positives because of latency or other things? Just curious.

Also not sure why you recommend to disable it, a simple search and you can find people sharing ones for auto control of recoil and spread for csgo and other games.

I will suppose that it detects any manipulation of button fire, not only rapid fire correct me if i'm wrong.

For example in this video the player was banned faster for macro (and i augmented detections to the double for safety) than the aimbot detection and it is obvious that he uses both no spread and anti recoil:
https://streamable.com/92jt92

Possibly could you elaborate on the max presses log ? It is generally always on "20"

**Comment by J-Tanzanite** [comment]
No, latency doesn't affect macro detections, so you don't have to worry about that.

I don't recommend disabling it, it is just disabled by default because most server owners don't care about macros.
Keep in mind that Lilac also runs on games where macros don't really matter, like TF2.
And in fact, a lot of CS:GO server owners don't care about macros either; Yes, many do, but many also don't.

>  will suppose that it detects any manipulation of button fire, not only rapid fire correct me if i'm wrong.

No, macro detection is just for detecting spam, like AHK.

Yes, 20 is the limit before something is considered a macro, as can be seen here:
`macro_max = (tick_rate >= 60 && tick_rate <= MACRO_LOG_LENGTH) ? 20 : 0;`
What this code says, is that Macro detection is only enabled if the game tickrate is higher (or equal to) 60 ticks per second and lower (or equal to) 200.

Why 20? It's due to a number of factors, like what AHK and such tools can consistently produce, the difficulty for most players to spam consistently without tools or scroll, etc.
