### ISSUE TITLE
L4D2 wrong bans.

### ISSUE THREAD

**Issue by a847427933** [J-Tanzanite/Little-Anti-Cheat#146]
While played Third-party maps with mini gun with this plugins,it will easy to get ban by detected Angle-Cheats.
I upload a video to youtube that you can watch it：https://www.youtube.com/watch?v=QK3NqKpajsc
at 1:46 you can see the banning log and cfg settings.
BTW I am using the 1.7.3 version,but all the version getting the same problem.

**Comment by a847427933** [comment]
The map is Cure 2
You can download on workshop
https://steamcommunity.com/sharedfiles/filedetails/?id=1756981457&searchtext=cure+2

**Comment by J-Tanzanite** [comment]
Sorry for the delayed response.
Thank you for reporting this.

Early on in Lilac's public development, some people reported angle problems for L4D1&2, and the issue was that pitch angles weren't normalized right for the Smoker, causing bans.
The fix was simple, since the pitch angle wasn't getting normalized correctly, I disabled angle checks for Pitch.
I figured the issue was only with Pitch for Smoker, and left it at that.

Looking at your video, it seems like not even Roll gets normalized right.
With Roll being the only angle now left checked in L4D1&2, and knowing even that is unstable, perhaps the best solution is to just disable angle checks for L4D1&2 entirely.

I'll update version 1.7.4 to ignore angle checks in L4D1&2.
You won't have to set `lilac_angles` to `0` in the future, the ConVar will simply do nothing in L4D1&2.
For now tho, you can set the ConVar to 0.

I'll reply here once I've uploaded the patch for this issue in version 1.7.4, after that, you can install it and the issue should be resolved.

As for past bans for Angle-Cheats in L4D1&2, I recommend unbanning.

**Comment by J-Tanzanite** [comment]
Ok, version 1.7.4 now has a fix for this, just download it from the releases tab.

**Comment by a847427933** [comment]
good.it works great now.

**Comment by J-Tanzanite** [comment]
Actually, according to the VALVe Wiki, roll should be locked at -50 to 50. And SMAC doesn't check roll for L4D2.
The fact that Pitch is broken too for certain characters doesn't bode well for angle checks in L4D1&2.

However @lunatixxx , this patch isn't permanent.
I want version 1.7.4 to get merged into the stable branch so that I can finally move on to version 1.8, which I plan on being a L4D2 update. It will take some time, but I want 1.7.x to be mostly over with.
