### ISSUE TITLE
how to change prefix from [lilac] to ur own prefix 

### ISSUE THREAD

**Issue by abbacialla** [J-Tanzanite/Little-Anti-Cheat#159]

**Comment by J-Tanzanite** [comment]
I can understand how some people do this to make their community/servers seem more professional, having their "own, selfmade" anti-cheat (which is just a lie, don't kid yourself).
Opensource allows for this kind of thing, which I am legally fine with, but ethically... Not so much. Especially not when I've seen people take Lilac, rename it, not make any other change, and then sell it to communities; meanwhile I get nothing...
These kinds of acts leave a bad taste in my mouth; especially since it makes people less aware of Lilac's existence.
I dunno, people renaming other people's works, contributing nothing and then asking for support, *especially* feels wrong.
You're on your own.
