### ISSUE TITLE
No started

### ISSUE THREAD

**Issue by denzel519** [J-Tanzanite/Little-Anti-Cheat#170]
[SM] Failed to load plugin "lilac.smx": Unable to load plugin (unsupported feature set; code is too new).
[v1.7.4_3]

**Comment by azalty** [comment]
Update sourcemod

**Comment by J-Tanzanite** [comment]
Lilac requires SM version 1.11

**Comment by denzel519** [comment]
It’s a pity, unfortunately I can’t translate into css to cm 11, half of the plugins will stop working

**Comment by J-Tanzanite** [comment]
Other plugins will stop working if you use SM 1.11?
Out of curiosity, what plugins are those?

**Comment by denzel519** [comment]
I have not tested it yet, but many people said that natives are new on sm 11. Just wondering why you excluded sm 10 and below?

**Comment by Rushaway** [comment]
> It’s a pity, unfortunately I can’t translate into css to sm 11, half of the plugins will stop working

Then update your plugins or in less than one year you will run a server fully outdated.

**Comment by azalty** [comment]
> It’s a pity, unfortunately I can’t translate into css to sm 11, half of the plugins will stop working

That's just false. The SourceMod installation on servers is backwards compatible: this means that if your server runs SM 1.11, you can run plugins that have been compiled in SM 1.7 and older.

**Comment by J-Tanzanite** [comment]
iirc, the necessity of SM 1.11 is due to a change done to ConVars in Lilac to show new convars in the config file when updating.

See, when I add new convars to Lilac, those convars aren't automatically added to people's config files, meaning a lot of people would have to delete their configs, regenerate them and fix their settings just to see what's new.
Azalty suggested using convar replacement by kidfearless, but that fix used a feature only available in SM 1.11.

That is, if I am remembering correctly.

But as others have stated, give SM 1.11 a try, it's probably going to work.
