### ISSUE TITLE
Will this work alongside fork of smac

### ISSUE THREAD

**Issue by TonyS95** [J-Tanzanite/Little-Anti-Cheat#2]
https://github.com/Silenci0/SMAC
will this work alognside with this?

**Comment by TonyS95** [comment]
and would it be possible for you to use the "updater" extension so dont have to pull it manually everytime from the repo

**Comment by J-Tanzanite** [comment]
Yes, Little Anti-Cheat will work alongside SMAC without problems.

However, if you plan on using SMAC's ConVar checker, I highly recommend you turn off the ConVar checker in Little Anti-Cheat, by setting **lilac_convar** to 0 in **cfg/lilac_config.cfg**
This is because SMAC's ConVar checker is more advanced than Lilac's ConVar checker. And running two convar checkers checking some of the same stuff is inefficient.
Lilac's ConVar checker is very basic.

But, if you enable **lilac_backtrack_patch**, that might cause false eye_test detections in SMAC's eye-test module (depending on which plugin gets loaded first).
The backtrack patch is disabled by default, so you don't have to worry about it unless you enable it.

In general, I wouldn't recommend using the eye_test module from SMAC at all, since it has a long history of being prone to false positives for a lot of people.

I haven't thought or heard about the updater extension, but I'll look into it.

Lastly, lilac.sp is currently version 1.1.0, whereas the precompiled plugin (lilac.smx) is version 1.0.0.
Version 1.1.0 is under testing atm and should fix some issues people were having with aimlock detections.
The precompiled version (1.0.0) is the stable release tho.

**Comment by TonyS95** [comment]
Yeah i've tried using the .sp compiled it but it didin't worki uploaded it to the server didin't create any cfg files neither in /sourcemod/configs nor in /cfg/sourcemod

**Comment by TonyS95** [comment]
My bad i got it it was straight in the cfg not /cfg/sourcemod might wanna change it to that because itll confuse alot of people

**Comment by J-Tanzanite** [comment]
Unfortunately, there are now server owners who use the **cfg/lilac_config.cfg** file already, changing the default file location would cause confusion and potential problems for those who already have edited their config.

So I can't change it, though, I should make it more clear in the README.MD where the file is, to avoid confusion like you point out.

Anyway, this issue/question has been answered/resolved, so I'm going to close this now.
If any other issues arise, just open a new issue and I'll have a look :)

**Comment by CanadianJeff** [comment]
I am almost curious why make lil anticheat when smac is already a thing.....
can lilac code be put into smac and/or smac code put into lilac???

will lilac make smac obsolete at all??? is that the goal??? or just have lilac run along side of smac and have both??

**Comment by J-Tanzanite** [comment]
> I am almost curious why make lil anticheat when smac is already a thing.....

SMAC is an old abandoned project that most cheats are able to bypass with ease.\
I'm aware that Silenci0 did take over the project, but at most, all he did was maintain the project and fix a few bugs. He never really added anything new.

---

> can lilac code be put into smac and/or smac code put into lilac???

Technically: Yes.\
Actually: No.\
You see, many years ago, there was a dispute over SMAC (I wasn't around back then, and my details may be a little off), due to some missing copyright headers.\
Because of this, one of the people who originally worked on SMAC, or at least, what SMAC copied, DMCA'd the project.\
I've seen people argue about who was in the right or not, and honestly, I do not know enough about it and I do not care.

I would not ever put SMAC's code into Lilac for this reason alone, the copyright.\
But that isn't the only issue, SMAC's coding style is very different to that of mine, and it would create a mess.\
Lastly, SMAC's code is outdated... Well that's at least my opinion. Some parts of SMAC's code is trivial to bypass and have issues.

That is not to say that SMAC is completely useless, some parts of it is actually really good, and SMAC does more than try to catch cheaters (it also patches some exploits). But overall, it's outdated. It may still catch some cheaters, but it's also not noticing a huge amount of them... And again, most cheats are able to bypass SMAC.

---

> will lilac make smac obsolete at all???

That entirely depends on the community and if they wanna abandon SMAC in favor of Lilac, which I doubt.\
Although some of them have.

---

> is that the goal???

My entire goal with this Anti-Cheat was to help the community out, as SMAC has become outdated and can't catch a lot of cheaters.\
In addition to this, development of SMAC ended long ago, and due to the drama surrounding it, I'm honestly not surprised very few people wanna work on it.

---

> or just have lilac run along side of smac and have both??

Again, that's up to the community.
