### ISSUE TITLE
Am not sure if this is a bug

### ISSUE THREAD

**Issue by TonyS95** [J-Tanzanite/Little-Anti-Cheat#22]
every ban that happens through sourcebans it has "bhop detected" when they are spin botting or anything

**Comment by J-Tanzanite** [comment]
I'm not sure I understand what you mean.
Little Anti-Cheat doesn't detect spinbot...

I'm guessing you mean that cheaters who use aimbot and other cheats get banned for Bhop?
Which wouldn't surprise me, cheaters can use more than just one cheat.

... I have a feeling that isn't what you mean tho, can you elaborate further?

**Comment by TonyS95** [comment]
Yeah its not what i mean everybody that gets banned is for "bhop Detected" i had one say "bhop ekektc" something along the lines but i was spectating them they were cleraly using wh and never bhopped at all

**Comment by J-Tanzanite** [comment]
"bhop ekektc", I think you mean "Bhop entdeckt", which is the German translation of "Bhop Detected".
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/translations/de/lilac.phrases.txt#L48

Ban and kick reasons are translated to the language of the player who gets kicked/banned, just in case they don't speak English too well, as they should have the opportunity to understand why they were thrown out of the game.

As for Bhop banning players who aren't Bhopping, it may not always be clear that they are actually Bhopping.
If someone is walking up a ramp (Like stairs or so) and they Bhop, it won't show too well (if at all).
Another thing is that cheats can mess with all manners of things, which can sometimes make it hard to see what's actually going on.

Because of this, if you can't replicate any steps on how to trigger this, I wouldn't worry about it. :)

**Comment by J-Tanzanite** [comment]
Since this issue has gone quiet for a while now, I am going to close it.
If you do find a way to replicate the issue or have more information, just comment it and I will see :)
