### ISSUE TITLE
Lost in Translation

### ISSUE THREAD

**Issue by migpics** [J-Tanzanite/Little-Anti-Cheat#34]
Is there any benefit in renamining the detected cheats to go along better with the native language?
For instance, in Spanish, it calls out "Detectado Angle-Cheats" saying it has detected Angle-Cheats.  But would a better translation be "Tramposo Angulo Detectado" or "Detectado Angulo-Cheats" as the description of Angle is descriptive, not just a name.

**Comment by J-Tanzanite** [comment]
I don't speak Spanish, I only know two languages, English and Norwegian.

I tend to give translators as much leeway as possible when they make translations, as the point of translations isn't accuracy, but getting the point across. As people banned or kicked for something should have the opportunity to understand why.

For instance, there is no word for "Aimbot" in Norwegian, but Norwegians understand what "Aimbot" means; we say it all the time when calling out cheaters (I should know as a Norwegian).
It is possible to be very descriptive and translate it to "Automatisk sikting og skyting", which roughly translates to English as "Automatic aiming and shooting".
Although that would technically be a better translation as it is 100% (or as close to as possible) Norwegian and descriptive... It would be redundant if "Aimbot" is understood by Norwegians.

This is not to say that you are wrong, you may very well be right, I don't speak Spanish and cannot verify. Language is not just about grammar and knowing the vocabulary, but also knowing how other native speakers will understand what you say, and this isn't something you can learn from a book; there is a big cultural thing to languages (That I don't understand).

Since I don't speak Spanish, I cannot verify the accuracy of translations, I can at most use google to check if I am being trolled, but other than that, I just have to trust the translators.

If you think "Tramposo Angulo Detectado" (or "Detectado Angulo-Cheats") is better understood by Spanish speakers than "Detectado Angle-Cheats", then I would happily accept a merge request with those changes.
At the end of the day, these things can only be debated by native speakers, and I just have to trust them.

---

So to summerize and answer your question "Is there any benefit in renamining the detected cheats to go along better with the native language?"

It depends entirely on the language and the people speaking it: So yes and no.
As long as the message comes across and they understand why they were banned, I'm happy; as that's my goal.

**Comment by migpics** [comment]
Thank for the response.  
I was not sure if there was a standard protocol for these things but good to know!

**Comment by 4LEJ4NDRO** [comment]
https://github.com/J-Tanzanite/Little-Anti-Cheat/commit/e4bfbb5b39faa601c626d4c7e44632fb13012c02 L11, L17 and L33
all these translations are wrong, and the rest of the translations of "migpics" are not necessary, because they are well written both ways.

-"el consulado" = https://en.wikipedia.org/wiki/Consulate = https://es.wikipedia.org/wiki/Consulado . Is a data query...
-"Exploit" in spanish is "Vulnerabilidad", but it is not logical to translate it, because many other things should also be translated "Anti-Cheat" = "Anti-Trampas", "Chat-Cleaner" = "Limpiador-de-Chat",  "Anti-Duck-Delay" = "Anti-Demora-de-Agachado"...
-"Tramposo Angulo Detectado" it is awful, the correct translation is "Detectado Angle-Cheats" = "Detectadas trampas de ángulo" or "Trampas de ángulo detectadas"

migpics, Estas usado un contexto erróneo en palabras como "el consulado" y "aprovecho", además son traducciones pobres. Si traduces "Angle-Cheats" también se deben traducir palabras como Aimbot, WallHack... que estés adaptado a ellas no significa que debas traducir unas sí y otras no. Lo más lógico es conservar los nombres de trampas en inglés.

**Comment by migpics** [comment]
@J-Tanzanite  I yield to 4LEJ4NDRO's translations as apparently my regional dialect may not be accepted as standardized spanish.   4LEJ4NDRO, lo que estado mirando es que teniamos estas discussiones de como debemos de traducir las palabras porque soy de un region nortenia de mexico que combina muchas palabras de ingles i espanol.  Pero estas en el derecho, y gracias por ayudar con esto.

**Comment by J-Tanzanite** [comment]
Seems like the both of you have come to an agreement.
I've reverted the changes to the Spanish translations.
re-closing this, if any further disputes come along, feel free to reopen.
