### ISSUE TITLE
AimLock false ban

### ISSUE THREAD

**Issue by Lime18** [J-Tanzanite/Little-Anti-Cheat#39]
I have a false ban for aimlock, the fResh player, at 7.30 it bans!
https://gofile.io/d/9EiMFK

**Comment by J-Tanzanite** [comment]
I see what's going on.

Normally, when you teleport (Through a teleporter building in TF2) or spawn, Aimlock tests get disabled for a few seconds because your aim "snapped"/teleported.
As you can see here:
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/6f85930f641ead431a391e4eaeb0e397e67ac7d3/scripting/lilac.sp#L1244
``` c
// Player recently teleported or taunted, ignore angle snaps.
if (GetGameTime() - playerinfo_time_teleported[i] < 2.0)
	continue;
```

However, the teleport exception only counts when you spawn or take a teleporter building (TF2).

---

Having watched your demo, I'm not sure if it's the map that teleports the player, or if it's a plugin which does it.

---

### If it's a plugin:
As far as I know, there isn't a way to detect when plugins teleport players, plugins that do so need to tell Lilac to not test for Aimlock through the Forward Lilac provides:
``` c
public Action lilac_allow_cheat_detection(int client, int cheat)
{
	// Psudocode... Implementation depends on the teleport plugin author.
	// Block the detection.
	if (teleported_player_recently(client) && (cheat == CHEAT_AIMLOCK || cheat == CHEAT_AIMBOT))
		return Plugin_Stop;

	// Allow the detection, it wasn't an aimlock/aimbot detection, or the player didn't teleport recently.
	return Plugin_Continue;
}
```

---

### If it's the map:
Then I'm not sure how I would detect that...
I'll look into it...

---

Which one is it?
Is it a plugin that teleports players or is it the map?

**Comment by Lime18** [comment]
This is plugin DUELS https://github.com/boomix/csgo-duels

**Comment by J-Tanzanite** [comment]
I see, it's the plugin "duels" which is doing it.
You should ask the developer of that plugin to add the code I showed above to fix it.

...
Tho, it doesn't seem like that developer is active all that much anymore...?

---

I tried to fork his plugin and fix it myself, you can find my fix here: https://github.com/J-Tanzanite/csgo-duels
# NOTE!
This fork is **experimental!** And may have **issues and may not work!**
It should in theory work, I only changed one thing, which was to block Aimlock detections if a player recently teleported.
Try it out and see if that fixes your problem.

**Comment by Lime18** [comment]
Thanks, I'll try this.

**Comment by J-Tanzanite** [comment]
Did it work?

**Comment by Lime18** [comment]
Yes, it seems to work.

**Comment by J-Tanzanite** [comment]
Awesome!
I'll close this issue then, if you get further problems, just reopen this issue :)
