### ISSUE TITLE
[Bug] Doesn't work for Non-Steam versions. (Ans: I don't support them, and won't either)

### ISSUE THREAD

**Issue by JustFanku** [J-Tanzanite/Little-Anti-Cheat#51]
Hello faced a problem, I have a server Css v91, SM 1.10 system bans materialadmin, a friend antichit works fine on the same server, also the material admin, I also do not work correctly bans for 1 minute without specifying the reason for the ban, in the log of the detector writes that ban for aimbot, in the config ban is registered on permament, please help, oh yes, the version of MATERIAL Admin 1.1.5.4 (517)

**Comment by J-Tanzanite** [comment]
> Css v91

Question, isn't that a free cracked version of the game?
As in, non-steam?

**Comment by JustFanku** [comment]
> > Css v91
> 
> Question, isn't that a free cracked version of the game?
> As in, non-steam?
> 
> (Edit: In case my question wasn't clear - is CS:S v91 from steam? Or is it an old cracked version of the game?)

No-steam server

**Comment by J-Tanzanite** [comment]
I'm aware that you aren't English, and so I will say this: cracked = non-steam.
In case you are using google-translate, that may get mistranslated... So when I say "cracked", I am referring to non-steam.

---

I'm sorry but, I will not  support the cracked/non-steam versions.

I've said this before, but considering this issue has gotten brought up several times now, I think I might have to put up a PSA, saying that Lilac does not support cracked/non-steam versions of any game, and that I will not work on it.

I only support the official versions from VALVe, on steam.
I do not understand why people use the non-steam versions in the first place, as the game is dirt cheap.

But also, these cracks tend to be from older versions of the game, which behave differently to that of the new versions. Which sometimes means they have bugs, and some of them actually cause false positives (Like Angle-Cheats, been told by someone who uses a cracked/non-steam version that Angle-Cheats don't work, because the older outdated games don't normalize angles).
So on a technical basis, supporting these non-steam versions is terrible, because they don't behave normally in the first place.
If there are any bugs, they don't get fixed, and that's a problem.

But there is also another reason why I won't support non-steam versions:
I don't support piracy.

If you want the game, buy the game.
If you want support, use the updated legal version.

I will not look into why a **modern** Anti-Cheat written in 2018-2020(soon 2021) that supports **modern** versions of the game - don't work for old outdated cracks.
If this is important to you, then you'll have to talk to someone who is willing to investigate what the problem is.

Other Anti-Cheats (like SMAC) may work fine, but they also don't check a whole lot of things.

Sorry, but I cannot and will not help. :(

**Comment by JustFanku** [comment]
> I'm aware that you aren't English, and so I will say this: cracked = non-steam.
> In case you are using google-translate, that may get mistranslated... So when I say "cracked", I am referring to non-steam.
> 
> I'm sorry but, I will not support the cracked/non-steam versions.
> 
> I've said this before, but considering this issue has gotten brought up several times now, I think I might have to put up a PSA, saying that Lilac does not support cracked/non-steam versions of any game, and that I will not work on it.
> 
> I only support the official versions from VALVe, on steam.
> I do not understand why people use the non-steam versions in the first place, as the game is dirt cheap.
> 
> But also, these cracks tend to be from older versions of the game, which behave differently to that of the new versions. Which sometimes means they have bugs, and some of them actually cause false positives (Like Angle-Cheats, been told by someone who uses a cracked/non-steam version that Angle-Cheats don't work, because the older outdated games don't normalize angles).
> So on a technical basis, supporting these non-steam versions is terrible, because they don't behave normally in the first place.
> If there are any bugs, they don't get fixed, and that's a problem.
> 
> But there is also another reason why I won't support non-steam versions:
> I don't support piracy.
> 
> If you want the game, buy the game.
> If you want support, use the updated legal version.
> 
> I will not look into why a **modern** Anti-Cheat written in 2018-2020(soon 2021) that supports **modern** versions of the game - don't work for old outdated cracks.
> If this is important to you, then you'll have to talk to someone who is willing to investigate what the problem is.
> 
> Other Anti-Cheats (like SMAC) may work fine, but they also don't check a whole lot of things.
> 
> Sorry, but I cannot and will not help. :(

i agree the game itself is not expensive, and yes, i'm from russia, i have a steam version of the game, we have such a community it's easier for them to download than buy, it's a pity that i didn't find help here, everything is good.

**Comment by J-Tanzanite** [comment]
I do agree it's a pity that I won't support non-steam versions, as you explain, there are legitimate reasons why people use the non-steam version.

But even if I put aside my dislike of piracy - the technical issues with non-steam versions (such as bugs and quirks) make support really hard, and in some cases, impossible without nerfing the AC.

The issues you'll get are possible to fix, but I can't do them.
Little Anti-Cheat is free and open source, and you'll probably be able to ask someone else to look into it and get it fixed, I certainly hope so at least. :)

I'm sorry I can't be of more help. :(
