### ISSUE TITLE
SourceBans++ Not Detected

### ISSUE THREAD

**Issue by Shaneajm** [J-Tanzanite/Little-Anti-Cheat#58]
Hello! I have Sourcebans++ installed on my server but for some reason the plugin wants to default to BaseBans.

I did edit the .sp file briefly but I did have the sourcebanspp.inc in my include directory so it should've grabbed it. I even changed the `tryinclude` for SourceBans to `include`. This is the message I get in console:

```Checking ban plugins:
Material-Admin:
	Loaded: No
	Native Exists: No
	ConVar: lilac_materialadmin = 1
	WARNING: Material-Admin was NOT included when compiled, banning through MA won't work!
	Предупреждение: Material-Admin НЕ БЫЛ включен при компиляции, баны через MA не будут работать!
Sourcebans++:
	Loaded: No
	Native Exists: No
	ConVar: lilac_sourcebans = 1

Banning will go though BaseBans.
```
Any ideas as to why? I should mention that this is on CS:GO.

**Comment by J-Tanzanite** [comment]
Assuming you didn't remove the warning, it did indeed include the sourcebanspp.inc file.
Otherwise, it would have given you a warning, like it did for Material-Admin.

As you can see by the message, it hasn't detected that SourceBans++ (the plugin) is running...
And it hasn't detected the Ban Native it creates.
So it seems to be a SourceBans++ issue, so I have to ask some questions.

What version of SB++ are you running?
Did you modify SB++ by any chance?
SourceMod version and MM:S version? (This often is the issue)

Have you tried the pre-compiled version of Lilac?
The pre-compiled version comes with SB++ and Material-Admin support out of the box, and if the pre-compiled version works, then the issue might lie with the server setup or with SB++.

Also, do you have any other plugins that work with SB++?

Lastly, I am making the assumption that you know the difference between SB and SB++, because some people assume I support both... I only support SB++.
But based on your file name, I don't think you've confused the two.

**Comment by Shaneajm** [comment]
SB++ is version 1.6.3 and I have not modified it. When using the precompiled version I still get the same message.

**Versions:**
SourceMod 1.10.0.6462
Metamod:Source 1.10.7-dev

I do have an older version of CowAC that does work with SB++ bans are correctly handled through there. It could be because the SourceMod and MetaMod installs are pretty old. I'll run an update and see if that fixes it.

**Comment by Shaneajm** [comment]
Got it working, re-install of Sourcebans++ fixed it!
