### ISSUE TITLE
[TF2] False Angle-Cheat detection on BumperCarts when used outside of Halloween map areas.

### ISSUE THREAD

**Issue by WOLFA22** [J-Tanzanite/Little-Anti-Cheat#59]
There is a bug on some maps, when the TF2 player uses the bumper car, and climbs on a rock or similar crap - the camera moves to a place somewhere behind the rock or an object and we disconnected with the reason: Blocked for viewing angles.

Please add the detection of such moments with the camera and ignore them in anticheat.

If necessary - I can bring video evidence.

Lilac 1.6.1 used..
Bumper cars plugin:  https://forums.alliedmods.net/showthread.php?t=250759

**Comment by J-Tanzanite** [comment]
A video would be nice. :)

But the fix can't be implemented in Lilac.
Here is why:

If I were to add exceptions if a plugin is installed or check for special conditions from other plugins, Lilac would be 50000 lines long, preform badly and possibly lag the server.
Most of the plugins that would be added for the special-case checks, wouldn't even be installed on most servers... Meaning Lilac would check for things that aren't even installed, it doesn't make sense to do it this way at all.

It would make FAARRR more sense for plugins that change gameplay or do special niece things to use the forwards Lilac provides.
In fact, this is what happened with https://github.com/boomix/csgo-duels .
Due to the plugin changing how the game worked and teleporting people's views all the time, it could trigger a false positive for Lilac. The proper way to fix that was to change the plugin to tell Lilac when it had messed with a player's view angles, like so: https://github.com/boomix/csgo-duels/blob/d2794c98ae598091dcb0547ec267414cd0dd75b2/addons/sourcemod/scripting/1v1dm/1v1_AntiCheat.sp
This goes for all Bhop plugins as well, if I were to add all of them into a large collection of exception checks - Lilac would lag, because it would check for things most servers don't have... Plus, it would be a nightmare to continuously update Lilac to handle other people's plugins... It's far more efficient, clean and better for everyone to just update the offending plugin itself.
Like so: https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/44#issuecomment-707508632
This is what SMAC does as well btw, it also provides Forwards so other plugins can tell it to ignore something.

You could also just make another plugin to tell Lilac this, instead of updating the bumpercart plugin.
Psudocode: 
``` c
#include <sourcemod>
#include <tf2>
#include <tf2_stocks>

// From lilac.sp, won't ever change.
#define CHEAT_ANGLES 0

public Plugin myinfo = {
	name = "[Lilac] Bumper cart exception",
	author = "J_Tanzanite",
	description = "Tells Lilac to ignore players who are in bumper carts.",
	version = "1.0.0",
	url = ""
};

public Action lilac_allow_cheat_detection(int client, int cheat)
{
	// Player is in bumper cart, ignore.
	if (cheat == CHEAT_ANGLES && TF2_IsPlayerInCondition(client, TFCond_HalloweenKart))
		return Plugin_Stop; // Tells Lilac to ignore this detection.

	// Player wasn't in cart, or was detected of something else.
	//     Don't tell Lilac to ignore detection.
	return Plugin_Continue;
}
```

If the bumpercart plugin can't be updated to tell Lilac that it has changed someone's views or messed with player data - or an external plugin like this isn't something you wanna do - then the only option left is to set `lilac_angles` to `0`.
Which isn't ideal, but that's how it is.

**Comment by WOLFA22** [comment]
https://youtu.be/T5gHNyvMgKw

**Comment by J-Tanzanite** [comment]
Hmm, I see.
It's more of a TF2 bug than a plugin issue, seems like the cart is programmed to try to align itself with any plane, regardless of the angle... Which means it will go outside of the abs(89.0) limit.
But at the same time, this would only happen if the cart is given to players where such inclines exist, so it's technically a plugin issue, as on official vanilla servers, this isn't an possible afaik.

I guess since this isn't entirely a plugin issue, but a weird quirk/bug with the game itself, I'll make a small update.

I wouldn't really worry too much about the bumper carts causing false positives for most servers, as carts are only really meant to be used on official maps, where such inclines shouldn't exist in the first place.
So this issue is pretty much limited to community servers where carts are provided on command, or through special community maps. Still, I'll do a small update limited to github, as version 1.7.0 will be released soon (no ETA).

**Comment by J-Tanzanite** [comment]
Right, version 1.6.2 has been released, try it out and tell me if it works. :)

**Comment by WOLFA22** [comment]
Yes, everything is fine, thank you, I checked.
