### ISSUE TITLE
[CS:GO] Bhop Detect with lilac_bhop 2

### ISSUE THREAD

**Issue by RusJJ** [J-Tanzanite/Little-Anti-Cheat#61]
Just leaving it there, lol: ... was detected and banned for Bhop (Jumps Presses: 556 | Bhops: 10)

**Comment by J-Tanzanite** [comment]
BHop detection comes down to probability, so it's never gonna be perfect.
Hence why BHop bans are by default 30 days.
It's re-worked in 1.7.0, which is currently in beta.

That ban just looks like someone who was unlucky, you should probably unban ¯\\\_(ツ)_/¯

**Comment by RusJJ** [comment]
Already did it, lol ;D
Set it to 1, btw thanks for the great work.

**Comment by rlevet** [comment]
Jumps Presses: 556

Which comes down to 55.6 +jump inputs per bhop which is like nearly impossible hehe

@J-Tanzanite btw idk if it's a personal choice but if you keep the space button pressed, it counts as a jump press for each tick the space bar is pressed. This is probably intentional with the method you use

**Comment by J-Tanzanite** [comment]
> idk if it's a personal choice but if you keep the space button pressed, it counts as a jump press for each tick the space bar is pressed. This is probably intentional with the method you use though, but if you plan on adding other detection methods, you should only count as one jump press.

It's not only intentional, but it gives more better context than counting how many times you pressed the jump button down.
See, cheats tend to do tick perfect input (Not always, but most do), and counting the +jump per tick shows this more clearly than counting how many times you went from no jump to +jump.

Although cheats could hold down the input for longer and fake being legit, it's currently not being done on a large scale.
This simply makes it easier to tell the difference between a likely-human input and scripts vs actual cheats.

---

In version 1.7.0-Dev 9 (Which has been released as a beta now :3) the BHop system is a little different, but logs the ticks you held +jump down for the same reason.

The difference there is that you can set it to ignore Min-BHops if the jump count is over a set limit.
An example of that would be if you set the jump-tick-limit to - say - 5. Then it would ignore Min-BHop detections if your jump ticks is larger than BHops done + 5 (it's a buffer).

"Min-BHops" is like a normal detection system btw, the first detection is ignored, but the rest are logged. Once the total BHop limit is reached, a ban occurs, and BHop detections expire after 10 minutes (Unsure on what the time should be, especially since different games and game modes are different.. tmp for now).

"Max-BHops" is the maximum consecutive perfect BHops before an instant ban is triggered (This value is meant to be high).

You can see all these things here:
Warning: These links point to the current version as of the time of writing, these links may point to older versions in the future. So future readers, keep that in mind :) 
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/fafec4f694082b0f4d63369180888fd17d9f4f7a/scripting/lilac/lilac_bhop.sp#L38
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/3e1645779328929b8ed1f7d9e7b8f28745637f04/scripting/lilac/lilac_config.sp#L619

**Comment by rlevet** [comment]
> 
> 
> Already did it, lol ;D
> Set it to 1, btw thanks for the great work.

btw he would still be banned with "1", but again I already discussed about it

**Comment by RusJJ** [comment]
Yeah, someone got banned tho.

**Comment by rlevet** [comment]
> Yeah, someone got banned tho.

I recommend disabling this feature until it's fixed

**Comment by J-Tanzanite** [comment]
> > Yeah, someone got banned tho.
> 
> I recommend disabling this feature until it's fixed

Yeah.
I mean, the default ban length is 1 month for a reason. But like rlevet (Ngl, your name is a finger twister) has pointed out, although the chance for a false positive is low, people can just keep Bhoping until they get banned (That's how you beat small odds, by rolling the dice constantly, so to speak). This is really common in Bhop servers and in jailbreak. 

It still does well in most servers, but the 1.6.X Bhop system is getting yeeted.
So disabling it is a good idea for a lot of people.

You can still tell by the jump counter how likely it was that someone was just unlucky.

---

Perhaps I need to clarify something: Version 1.6.X isn't going to get fixed, as version 1.7.0 is the new version that will become the official one, and 1.7.0 has a different Bhop detection system, so there's your fix.

1.6.X is currently only being updated with small fixes for small issues people bring up, while 1.7.0 undergoes testing to make sure it's stable, especially since the code was re-organized entirely.
Once 1.7.0 is declared stable, 1.6.X becomes outdated and everyone should update.

I'm still waiting for feedback on that version... Although the last comment I made in the discussion page about Bhop changes is somewhat out of date, I should probably comment there with the new correct information. brb, gonna do that :P 

---

That reminds me... Calling it "Jump Counter/Presses" is wrong, it should be named "JumpTicks"... Which is more descriptive of what it is... Especially since that's what it literally measures.

**Comment by rlevet** [comment]
I need to take a look at your changes

And yes I want to change my username but the thing is idk if I can do that on GitHub and the other thing is that it will break a lot of my scripts, repos, plugins

**Comment by J-Tanzanite** [comment]
I'm currently writing a comment explaining my changes, and how 1.7.0's Bhop system works.
So you can just sit back and relax while I finish it up. As my comment might clear up some weird stuff there. ;) 

Also, probably not worth changing your name then :/

**Comment by rlevet** [comment]
> 
> 
> I'm currently writing a comment explaining my changes, and how 1.7.0's Bhop system works.
> So you can just sit back and relax while I finish it up. As my comment might clear up some weird stuff there. ;)
> 
> Also, probably not worth changing your name then :/

Just learned github takes care of redirections, so that's neat
I'll just create a new account with my previous username and boom, it should work

**Comment by J-Tanzanite** [comment]
Eyy, that's neat :)

**Comment by J-Tanzanite** [comment]
Going to close this, as this is getting addressed/fixed in version 1.7.0, which can be found here: https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/restructured
