### ISSUE TITLE
Kicked For NoLerp???

### ISSUE THREAD

**Issue by CanadianJeff** [J-Tanzanite/Little-Anti-Cheat#74]
sm_cvar lilac_convar 0
sm_cvar lilac_nolerp 0

I set both of these to 0 and still getting kicked mind explaining this?

**Comment by CanadianJeff** [comment]
update it keeps getting reset back to 1 on map change thats odd

**Comment by CanadianJeff** [comment]
could we have the option to log but not actually kick? might be a temp work around for this issue because my server is 100 tick players like to set lerps at 0

**Comment by J-Tanzanite** [comment]
Which version of Lilac are you using?
Which game are we talking about?
Is this game a no-steam (cracked) version?

`sm_cvar` will change the ConVar, but when the map changes, the Lilac config gets executed, which changes it back to the Config value.
You can find the Config here: `cfg/sourcemod/lilac_config.cfg` or `cfg/lilac_config.cfg`
If you want to change the value, change it in the config.

`lilac_convar` has nothing to do with NoLerp, you might as well keep that on.
`lilac_nolerp` doesn't kick, it bans... What exactly is the disconnect message?

**Comment by CanadianJeff** [comment]
L4D2

**Comment by CanadianJeff** [comment]
editing the cfg seems to have fixed the problem but strange the cvar kept getting reset

**Comment by J-Tanzanite** [comment]
You keep mentioning players getting "kicked", but not "banned"... In relation to "lerp 0"? That doesn't make sense.

Since you didn't answer my other questions, I'm going to assume you're talking about Lilac 1.6.1
And I'm also going to make the assumption you're playing the steam version.

But I still want to know what disconnect message your players are getting.

**Comment by J-Tanzanite** [comment]
I'm going to close this due to lack of replies, and lack of details in general...
I can't help you if the info given is bare bones.

That said, version 1.7.0-Dev 13 is out, and has a fix for a NoLerp false positive, which was reported by someone else who gave more info, perhaps this was the issue you were having?

Anyway, if you wish to comment if that version fixed your issue or any other general feedback, don't feel shy :)
