### ISSUE TITLE
Feedback Version 1.7.0 Beta | Macro Auto-Jump

### ISSUE THREAD

**Issue by crashzk** [J-Tanzanite/Little-Anti-Cheat#75]
I would like to say that so far I have not noticed any errors or BUGS in version 1.7.0 Beta that I have been using on my servers.

However I noticed that on all my servers the log is always being updated, detecting the use of Macro Auto-Jump:
```
25/03/2021 - 06:44:22 [Version 1.7.0-Dev 12] {Name: "Rerize" | SteamID: STEAM_1:1:504906287 | IP: XXX.XXX.XX.X20} was detected of using Macro Auto-Jump (Detection: 2 | Max presses: 20).
	Pos={-651,-1156,-130}, Angles={21.00419,56.74383,0.00000}, Map="de_mirage", Team={3}, Weapon="weapon_knife_ursus", Latency={Inc:0.000035,Out:0.032072}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.000000,Out:0.000000}, ConnectionTime={370.328125 seconds}, GameTime={797.273437 seconds}
25/03/2021 - 06:45:41 [Version 1.7.0-Dev 12] {Name: "Rerize" | SteamID: STEAM_1:1:504906287 | IP: XXX.XXX.XX.X20} was detected of using Macro Auto-Jump (Detection: 3 | Max presses: 20).
	Pos={211,804,-121}, Angles={9.78725,160.41935,0.00000}, Map="de_mirage", Team={3}, Weapon="weapon_knife_ursus", Latency={Inc:0.000040,Out:0.035147}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.001953,Out:0.000000}, ConnectionTime={449.273406 seconds}, GameTime={876.218750 seconds}
25/03/2021 - 06:45:44 [Version 1.7.0-Dev 12] {Name: "Rerize" | SteamID: STEAM_1:1:504906287 | IP: XXX.XXX.XX.X20} was detected of using Macro Auto-Jump (Detection: 4 | Max presses: 20).
	Pos={-205,773,-101}, Angles={15.76652,-144.28475,0.00000}, Map="de_mirage", Team={3}, Weapon="weapon_knife_ursus", Latency={Inc:0.000041,Out:0.034387}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.000000,Out:0.000000}, ConnectionTime={451.664093 seconds}, GameTime={878.609375 seconds}
25/03/2021 - 06:45:46 [Version 1.7.0-Dev 12] {Name: "Rerize" | SteamID: STEAM_1:1:504906287 | IP: XXX.XXX.XX.X20} was detected of using Macro Auto-Jump (Detection: 5 | Max presses: 20).
	Pos={-591,571,-56}, Angles={21.28583,-175.30567,0.00000}, Map="de_mirage", Team={3}, Weapon="weapon_knife_ursus", Latency={Inc:0.000039,Out:0.034219}, Loss={Inc:0.003417,Out:0.000000}, Choke={Inc:0.003417,Out:0.000000}, ConnectionTime={454.023437 seconds}, GameTime={880.968750 seconds}
```
Would that be a false positive?

No player has been banned for this reason yet, but all my servers only have this detection in the anti-cheat log.

My servers do not have any plug-ins for Auto-BunnyHop or configuration to facilitate this, except AWP ONLY that I have a plugin for this, but limited to 5 hops and then have to wait 20 seconds to use it again and all servers configured at 128 tickrate.

However, even on servers without this plugin it still detects this macro.

I don't know if it helps, but they are all CSGO servers.

**Comment by crashzk** [comment]
If you want I have a complete log of all servers, I can send in private, since there is the IP of the players.

**Comment by J-Tanzanite** [comment]
Thank you for testing the Beta version, it really helps me develop Lilac :)

---

Anyway, Macro detection checks if a player is spamming a certain input all the time, the limit being 20 times a second.
Macros, AHK and Scroll (Scroll to jump) **can** be detected by this (Not always but tends to be, depends on the Macro/script/scroll and the frequency of how often it presses keys).
This was added because someone asked for it, it's not a bug.

Macro detection is disabled by default, because it's not something most server owners care about or need; plus it's not a big deal for most servers.

That said, perhaps I should add an option to prevent logging of Macro detection, but still detect it.
That way server owners who want to prevent Macro usage can do so without the log getting cluttered.

Also, regarding bans for Macros, by default, players get kicked for Macro usage, not banned (Because it's not a cheat feature).
You can change that behavior here: `lilac_macro_method`

Lastly, Macro bans only last 15-60 minutes.
`lilac_set_ban_length macro <minutes>` can't bypass this restriction.
The shortest amount of time a player can be banned is 15 minutes, and the longest 60 (1 hour).

**Comment by crashzk** [comment]
Perfect, thanks for explaining.

On the question of the log, wouldn't it be a good idea to create a separate log for each detection / verification mode?

Create a **`lilac`** folder and within it create the logs, separating each log for verification, Aim-Bot having its own log, Macro Auto-Jump having its log and so on.

**Comment by J-Tanzanite** [comment]
Hmm, I don't think server owners would like files to be separate, tbh.
People are accustomed to have single file for logs and configs, so that's unlikely to change.

Still, I'll put it on my todo list of adding an option to detect but not log Macros :)

**Comment by crashzk** [comment]
Just moving on to update, so far no errors with the plugin apparently.

Bans that are being applied most often would be by: **`Anti-Duck-Delay detected`**

Researching about it I found nothing, could you explain to me what would be the case, any video?

**Comment by J-Tanzanite** [comment]
Anti-Duck-Delay isn't actually the official name of the cheat feature, "Fastduck" is.
However, "Fastduck" doesn't really explain what it does, so I came up with another name to make it more intuitive.

Fastduck/Anti-Duck-Delay is a cheat feature which disables your duck-delay.
See, if you spam +duck and -duck (shift or ctrl), you will eventually "slow down" and duck and unduck slower, as your character gets "tired".

Cheats can bypass this by inserting an impossible input value (You can't insert this value normally).
This cheat feature is so common in cheats, that it's no wonder why most bans end up being Fastduck/Anti-Duck-Delay detections.

I don't think there's any video showing it? At least I'm not aware of one.

**Comment by J-Tanzanite** [comment]
Alright, I've updated the ConVar `lilac_macro` to have a "detect but not log" option now (Set it to 2).
That should prevent the Macro spam in logs, while still dealing with macro users.

**Comment by crashzk** [comment]
Doubt, I leaving the autoupdate cvar enabled:
```
// Automatically update Little Anti-Cheat.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_auto_update "0"
```
Do you update to the latest version of the **`restructured` branch** keeping the settings I currently use? Or do you replace them?

**Comment by J-Tanzanite** [comment]
I'm not entirely sure what you mean, but I think you're asking if updates can overwrite your config?
To which the answer is no.
Updates cannot change your config file, whatever preferences you've set, are kept. :)

**Comment by J-Tanzanite** [comment]
I am going to close this, as no further replies have been made.
Anyway, thanks for the feedback, it really helps :)

**Comment by crashzk** [comment]
> Alright, I've updated the ConVar `lilac_macro` to have a "detect but not log" option now (Set it to 2).
> That should prevent the Macro spam in logs, while still dealing with macro users.
@J-Tanzanite oops, sorry for the absence, I will test this new feature thanks.

Do I have to delete the current configuration file for it to update, or would there be some way to update all cvars, the configuration file without me having to delete it and configure it again?

**Comment by J-Tanzanite** [comment]
Sadly, you have to delete the config file and reconfigure it again. :( 

As far as I know, there is something called autoexecconfig (or something) that I could use, that would append new ConVars to the config file when I release new updates with new ConVars.
I just haven't gotten it to work... Yet :/

Hopefully in the future, I will have that setup so that you don't have to delete the config file and reconfigure stuff.
But as of right now, deleting and reconfiguring is the way.

**Comment by crashzk** [comment]
Apparently everything is fine with the question of the LOG regarding the Macro.

I will be closing these issues, any problems return the contact, thank you!
