### ISSUE TITLE
Auto-kick if client is turning very fast

### ISSUE THREAD

**Issue by stopmotio** [J-Tanzanite/Little-Anti-Cheat#78]
Basically anti-spinbot. It would have to be fast to avoid kicking people joking about with hi DPI mice.

**Comment by J-Tanzanite** [comment]
Having it be fast to avoid kicking legits isn't going to work, trust me.

That said, some people call anti-aim "spinbot", and that can cause some confusion in these types of discussions...
But from your post, I'm going to assume that isn't what you meant.

I used to have spinbot detection in Lilac back when it was a private AC, but it was pretty useless
(besides, it was TF2 only back then).
So I don't really see why this should be added, tbh.

**Comment by stopmotio** [comment]
I'm by no means an expert on any of this, it's just an idea I thought would work. Now that I think about it if it's set high enough that people can joke about with a high dpi (10000 or so) a spinbot would also work in that speed. If a spinbot is turning in one direction continuously that could filter it out since humans only have do much mousepad space

**Comment by J-Tanzanite** [comment]
Sorry for my late response, been busy lately.

Anyway, there are commands you can use in-game to turn at a fairly constant rate, +right/+left.
Plus, you can customize the speed via `cl_yawspeed`.
It is possible to detect when someone does this, but then cheats can mask themselves as doing it as well; making an exception check useless.

I know that spinning really fast can make it harder to get hit, the problem is that if someone is spinning really fast, then it makes it hard for them to hit anyone else as well.
Plus, Lilac does actually detect desync (sometimes) and spinbot if someone is aimbotting as well.
So there is kinda a detection for it.

**Comment by stopmotio** [comment]
Oh okay. Closing then.
Hey, at least your response time is way better than email support lol
