### ISSUE TITLE
Support for Bhop with Chance?

### ISSUE THREAD

**Issue by RusJJ** [J-Tanzanite/Little-Anti-Cheat#81]
Yesterday my player showed me an undetectable BHOP with chance. For example, 50% of bhop and LilAC wont detect bhop because of "3 bhop jumps, 1 regular jump, one more bhop jump". Dumb description...

**Comment by J-Tanzanite** [comment]
I know exactly what you mean, and I'm not going to do anything about it.
You see, at that point, the Bhop cheat is basically simulating a legit player, and telling that apart from a normal player is... A big gray zone. It's not something you'd want to do, because you will ban a couple of legits.

Now, there are some things that I CAN do that might even help detect those cases.
But it isn't worth it, because again, we're trying to split hairs at that point.
And server owners would rather have an AC that has few false positives and a few cheaters get away rather than many false positives and no cheaters (Especially since they can have admins to deal with the more discreet cheaters).

Plus, having something misfire like that can lead to distrust of the Bhop check as a whole (Especially when it's hard to explain to server owners how it works), meaning some server owners would rather turn it off entirely, leading to fewer cheaters getting banned at all.
So it's just a bad idea.

In addition to this, Lilac is a General Purpose AC, not specifically bound to 1 cheat detection.
Going this in-depth for something that will cause issues, distrust and is hard to explain to the average person - is just a waste of time and a bad idea.

**Comment by J-Tanzanite** [comment]
I am going to close this, as no further replies have been made.
And because I won't do more about it, as explained above.

If you have any other questions, requests or issues, feel free to create a new issue :)
