### ISSUE TITLE
Potential aimlock false positive

### ISSUE THREAD

**Issue by azalty** [J-Tanzanite/Little-Anti-Cheat#84]
One of my players claims he has been falsely banned.

Logs: https://pastebin.com/zmjN72YS

Ban details: https://games.ludosoft.net/sourcebans/index.php?p=banlist&searchText=STEAM_1%3A1%3A48697911+&Submit=Search

Demo: https://gofile.io/d/9pXAVO (starts at 23:11, round score 6-1)
Player name: Alexis.

He claims that he was using this: https://youtu.be/HYu_k-JGy60

I'm unable to tell if he is legit and this is a small positive. It seems like such an extreme case.

Thanks in advance <3

**Comment by J-Tanzanite** [comment]
Ok, I don't know what kind of mods you use on your server, but... Every player has MASSIVE boxes around them, blocking all sight... Had to use `r_drawothermodels 2` to see anything :'D

Anyway, the video says everything you need to know.
And looking at the demo confirms that this is probably what he's doing.

Basically, they're setting their sensitivity so high on the yaw axis so that they can do close to 180 degree turns while being able to look at people.
So as long as they look in someone's direction and then use the bind, they can keep doing near 180 degree turns and snap onto people.
That's it...

Looking at the comment section, people claim to have gotten OW banned from this, which I assume is a joke...
But it wouldn't surprise me if someone did try this and got banned.

The entire idea of using these commands to create this bind is to look like a cheater, by spinning in a way no normal person can usually do... While being able to shoot at people.

My view on this is pretty simple, if you have to go out of your way and do stupid stuff (that no sane or normal person would do) to look like a cheater, or to achieve things normally impossible and you get banned - you asked for it...
There's nothing really to fix, or that even can be fixed.

You can unban him and tell him not to do dumb stuff :P

**Comment by azalty** [comment]
No problem. Thanks for your answer!

I use custom content that you probably don't have, that's why :3
