### ISSUE TITLE
Support for Anti-WallHack

### ISSUE THREAD

**Issue by crashzk** [J-Tanzanite/Little-Anti-Cheat#89]
I wonder if you want to implement support for wallhack detection?

**Comment by J-Tanzanite** [comment]
Wallhack detection?
Don't you mean an Anti-WallHack (blocking wallhacks from working)?

It's _kinda_ possible to detect WallHacks, but very limited.
For example, the ConVar checker (lilac_convar) will check if `r_drawothermodels` is set to `2`, and if it is, then the player is WallHacking, and will get banned for an invalid ConVar...

But other than checking for invalid values in networked stuff - you can't detect WallHacks...
At best, you could do behavior analysis, which is error prone, difficult, doesn't scale well, and because different games have different gameplay - wouldn't always work across games... So that's not going to happen.

So I assume you are asking about an Anti-WallHack?
Something which blocks WallHacks from working, instead of detecting.

Sadly, I have to inform you that I am currently in the process of moving, and will spend the next year studying, so my time is drastically more limited nowadays than it was before.
So I won't be working on an Anti-Wallhack, that has sadly been canceled. Sorry :/

**Comment by freakexeuLow** [comment]
Maybe it help a little bit, andrewh had developed something like this before, it worked (currently I don't know if it still works now) problem will also be here that there is radar esp or also sound esp when an opponent approaches does..it's really hard to block everything, i still have anti sound esp and anti radar esp on the pc, playa, andrew amnd shadowkeeper had worked on it once....@J-Tanzanite if you are looking for contact, I can send you the files private, maybe it will help you..here the anti wallhack module: [https://github.com/87andrewh/CornerCulling](https://github.com/87andrewh/CornerCulling)

**Comment by crashzk** [comment]
That would be an Anti-WallHack in the case, thank you anyway.

I'll leave it for the record here, who knows in the future.

**Comment by J-Tanzanite** [comment]
I'm going to close this, as this thread serves no purpose anymore.

As stated earlier, maybe one day I'll work on this, but that would take a lot more time than I have nowadays, and without funding, I'm not going to do this now.
